#!/bin/bash

display_usage() { 
	echo "Usage: ./scripts" 
	
	} 
if [  $# -le 0 ] 
	then 
		display_usage
		exit 1
	fi 

export NACL_HOME=$HOME/pave/depot_tools/native_client/

./pal-sgx-sign -key enclave-key.pem -manifest hello.manifest.sgx -output sample2.sig -libsel $NACL_HOME/scons-out/sgx-linux-x86-64/staging/libsgx_entry.so -exec $1
./pal-sgx-get-token -output sample2.token -sig sample2.sig

