#!/bin/bash

display_usage() { 
	echo "Usage: ./scripts <module name>" 
	
	} 
if [  $# -le 0 ] 
	then 
		display_usage
		exit 1
	fi 


export NACL_HOME=$HOME/nacl/native_client/

./pal-sgx-sign -key enclave-key.pem -manifest hello.manifest.sgx -output tmp.sig -libsel $NACL_HOME/scons-out/sgx-linux-x86-64/staging/libsgx_nacl.so -exec $1
./pal-sgx-get-token -output tmp.token -sig tmp.sig
cp tmp.sig $NACL_HOME/signer/
cp tmp.token $NACL_HOME/signer/
